#!/bin/bash
# Manage VM nodes which have a specific set of hardware attributes.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FIRST_BRIDGE=${FIRST_BRIDGE:=docker0}
DEFAULT_MEMORY=2048
DEFAULT_CPU=2
DEFAULT_DISK=15

source "${DIR}/utils"

if [ "$EUID" -ne 0 ]
then echo "Please run as root"
     exit
fi

ACTION="$1"
shift
nodes=($@)

function main {
    if [[ $# -eq 0 ]]; then
        nodes=($(extract_session_key nodes))
    fi
    
    case "$ACTION" in
        "create") create_vm;;
        "start") start;;
        "reboot") reboot;;
        "shutdown") shutdown;;
        "poweroff") poweroff;;
        "destroy") destroy;;
        "vol-delete") vol-delete;;
        *)
            usage
            exit 2
            ;;
    esac
}

function usage {
    cat - <<EOF
USAGE: ${0##*/} <command>"
Commands:"
    create            create QEMU/KVM nodes on a rkt CNI metal0 bridge
    create-rkt        create QEMU/KVM nodes on a rkt CNI metal0 bridge
    create-docker     create QEMU/KVM nodes on the docker0 bridge
    create-uefi       create UEFI QEMU/KVM nodes on the rkt CNI metal0 bridge
    start             start the QEMU/KVM nodes
    reboot            reboot the QEMU/KVM nodes
    shutdown          shutdown the QEMU/KVM nodes
    poweroff          poweroff the QEMU/KVM nodes
    destroy           destroy the QEMU/KVM nodes
    vol-delete        delete QEMU/KVM disk
EOF
}

COMMON_VIRT_OPTS="--pxe --os-type=linux --os-variant=generic --noautoconsole --events on_poweroff=preserve"

function check_and_create_internal_bridge {
    local br=$1

    if [ -z "$br" ]; then
        br="kube0"
    fi

    if [ ! -z "$(brctl show $br 2>&1 | grep 'No such device')" ]; then
        brctl addbr $br
        ip link set dev $br up
    fi
}

function create_node {
    local node=$1 network="" \
          memory="$(extract_session_key $1 memory)" \
          cpu="$(extract_session_key $1 cpu)" \
          disk="$(extract_session_key $1 disk)"
    [ ! -z "$node" ] || return 0

    for mac in $(extract_session_key $node mac | tr ',' ' '); do
        if [ -z "$network" ]; then
            network="--network=bridge:${FIRST_BRIDGE},mac=$mac"
        else
            check_and_create_internal_bridge
            network="$network --network=bridge:kube0,mac=$mac"
        fi
    done

    virt-install --name $node $network --boot=hd,network \
                 --memory ${memory:-$DEFAULT_MEMORY} --vcpus ${cpu:-$DEFAULT_CPU} \
                 --disk pool=default,size=${disk:-$DEFAULT_DISK} \
                 $COMMON_VIRT_OPTS
}

function create_vm {
    local network="" memory="" cpu="" disk=""
    for n in ${nodes[@]}; do
        create_node $n
    done
}

function start {
    for node in ${nodes[@]}; do
        virsh start $node
    done
}

function reboot {
    for node in ${nodes[@]}; do
        virsh reboot $node
    done
}

function shutdown {
    for node in ${nodes[@]}; do
        virsh shutdown $node
    done
}

function poweroff {
    for node in ${nodes[@]}; do
        virsh destroy $node
    done
}

function destroy {
    for node in ${nodes[@]}; do
        virsh destroy $node
    done
    for node in ${nodes[@]}; do
        virsh undefine $node
    done
    virsh pool-refresh default
    for node in ${nodes[@]}; do
        virsh vol-delete --pool default $node.qcow2
    done
}

function vol-delete {
    virsh pool-refresh default
    for node in ${nodes[@]}; do
        virsh vol-delete --pool default $node.qcow2
    done
}

main $@
